In [32]:
import numpy as np
np.array([1,2,3,4])



array([1, 2, 3, 4])

In [33]:
a=list(range(3,10))
a

[3, 4, 5, 6, 7, 8, 9]

In [1]:
def greet(name):
    print("HI", name)

greet('amay')

HI amay


In [35]:
a=[1,3,2,7,9,7,4]
a.remove(7)
print(a)

[1, 3, 2, 9, 7, 4]


In [36]:
a=[12,'ankki']
print(a)

[12, 'ankki']


In [53]:
a=[12,23]
for i in a:
    b=i*2
    print(b)



24
46


In [54]:
a=np.array([12,23])
b=a*2
print(b)

[24 46]


In [55]:
a=[12,23]
b=a*2
print(b)

[12, 23, 12, 23]


In [57]:
a=np.arange(1,9,2)
print(a)

[1 3 5 7]


In [5]:
a=np.arange(1,10)
b=np.array([2,3,4])
print(a[b])

[3 4 5]


In [64]:
a = np.arange(1, 5)
result = np.prod(a)

print(a)
print('resulit=',result)
print(f'result={result}')

SyntaxError: invalid syntax (2261011685.py, line 5)

In [4]:
a = np.array([1, 2, 3])
max = np.amax(a)
print(max)

3


In [68]:
a=np.arange(1,5)
b=np.reshape(a,(2,2))
print(b)

[[1 2]
 [3 4]]


In [6]:
import numpy as np
a=np.arange(3,10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
a=np.arange(1,10)
b=np.array([2,3,4])
print(b)

[2 3 4]


In [9]:
a=np.arange(1,5)
b=np.reshape(a,(2,2))
print(b)

[[1 2]
 [3 4]]


In [13]:
a=np.arange(1,5)
b=np.reshape(a,(2,2))
b

array([[1, 2],
       [3, 4]])